name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update system
      run: |
        sudo apt-get -y update
        sudo apt-get -y upgrade

    - name: Install dependencies
      run: |
        sudo apt-get -y install golang-go
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    - name: Build and Install dalfox
      run: |
        go install github.com/tomnomnom/waybackurls@latest
        sudo cp /home/runner/go/bin/waybackurls /usr/local/bin



    - name: Run paramspider and Gxss
      run: |
        cargo build --release



    - name: Test        
      run: |
        ./target/release/x8 -u "http://testphp.vulnweb.com/search.php" -w "burp-parameter-names.txt"

        


